module.exports = function(_this){
    return{
        uploadImgBase64:{
            method:'POST',
            urlData:{}
        },
        getJSApiConfig:{
            method:'POST',
            urlData:{}
        },
        getWXOauthCode:{
            method:'POST',
            urlData:{}
        },
        addAccessStatistics:{
            method:'POST',
            urlData:{}
        }
    };
};
